### PR TITLE
Support multiple registries (#13)

### PR DESCRIPTION
**Pull request by squarebracket**
Cherry-pick of #13 (c5d6b09) to master.

### CODE REVIEW

**Comment by thesattiraju** [comment]
Update: I've pushed it to the market place, you should be able to. use it use `@v1` tag! 😃

**Comment by squarebracket** [comment]
You should really not delete and republish tags as another commit. That's considered very bad practice since others may rely on the specific code for a particular tag. Also, automated dependency updaters like dependabot and renovate won't be able to notice that a new version has been released, since there's no new tag/version.

You might also want to update the package.json to reflect the published action version as well, for posterity.

**Comment by thesattiraju** [comment]
True. But this isn't a breaking change as such, so it's okay to override I suppose. 

I agree with this
> Also, automated dependency updaters like dependabot and renovate won't be able to notice that a new version has been released, since there's no new tag/version.

I'll check with my team on this; this is the convention we're following! So, that you can use the new feature without updating your workflow, provided it ain't a breaking change.

**Comment by squarebracket** [comment]
> I'll check with my team on this; this is the convention we're following! So, that you can use the new feature without updating your workflow, provided it ain't a breaking change.

I find [SemVer](https://semver.org/) very useful in this regard; major version bumps represent backwards-incompatible changes, so any minor or patch version bumps are safe (automated dependency checkers usually have settings for whether to update across major versions or not, why is why I bring it up).

Also, I'd kind of assumed the rationale for a `releases/v1` branch was that it'd track the latest changes for that version. So you could have `Azure/docker-login@releases/v1` in your `.yml`, which would pull the latest code for that major version.

**Comment by squarebracket** [comment]
In any case, thanks for the merge!

**Comment by thesattiraju** [comment]
>automated dependency checkers usually have settings for whether to update across major versions or not, why is why I bring it up 

This would hold true for a node package publish; but probably not for actions. I'm not aware of any auto-updaters for actions in general.

**Comment by thesattiraju** [comment]
>In any case, thanks for the merge!

Thank you for the contribution 😄

**Comment by squarebracket** [comment]
> I'm not aware of any auto-updaters for actions in general.

Both [dependabot](https://dependabot.com/#languages) and [renovate](https://github.com/renovatebot/renovate/issues/5733) have some alpha-level support for actions, which is pretty cool.

**Comment by thesattiraju** [comment]
>Both dependabot and renovate have some alpha-level support for actions, which is pretty cool.

Sweet! It makes sense to have a SemVer kind of versioning. I'll deliberate with my team about this! 😃

**Pull request merged**
