### PR TITLE
Update Node.js to 16 - Node.js 12 is deprecated

### PR DESCRIPTION
**Pull request by StoyanStAtanasov**
Node.js 12 reached end of security updates at the end of April 2022 #43

### CODE REVIEW

**Comment by paksydavid** [comment]
Any chance of moving forward with this PR? Would be greatly appreciated. 🙏🏽

**Comment by jaketclarke** [comment]
Echoing comments above, be great to get this done :)

**Comment by simonziegler** [comment]
Hi - another request for the branch to move ahead. Github is whinging at me about my actions, and I'd love to get rid of the messages!

**Comment by hargut** [comment]
Node 12 will be dropped from the images on November 14th.

https://github.com/actions/runner-images/issues/6482

**Review by northtyphoon — APPROVED** [review]
LGTM

**Comment by mechelewskim** [comment]
@StoyanStAtanasov, could we please merge it?

**Comment by StoyanStAtanasov** [comment]
> @StoyanStAtanasov, could we please merge it?

I cannot. I can only close, but not merge :(

**Comment by mechelewskim** [comment]
@northtyphoon, can you help us?

**Comment by StoyanStAtanasov** [comment]
The close was a mistake, I thought it will give me an option to merge or something ...

**Comment by flcdrg** [comment]
@Josh-01 Is this something you can follow up?

**Comment by BALAGA-GAYATRI** [comment]
Can you please raise a PR against `releases/v1` also along with node_modules changes (if any) as that's the release branch. Also please add the test cases for which this PR is tests. Thanks!

**Review by azooinmyluggage — APPROVED** [review]
LGTM

**Comment by StoyanStAtanasov** [comment]
@BALAGA-GAYATRI made a new pull request against releases/v1 - #45

**Comment by StoyanStAtanasov** [comment]
I still cannot merge even after approval from @azooinmyluggage 
image

**Comment by BALAGA-GAYATRI** [comment]
Can you also please raise a PR against `releases/v1` branch also along with node_modules changes(if any).

**Comment by flcdrg** [comment]
@StoyanStAtanasov you do not have permissions to merge the PR. That will have to be done by someone like @BALAGA-GAYATRI

**Comment by jsinh** [comment]
Any chance this will be actually merged and a new version supporting Node 16 will be out soon? @StoyanStAtanasov @flcdrg, I appreciate it in advance. Thanks

**Comment by flcdrg** [comment]
While we wait for this to be resolved, apparently according to the 'Mitigation notes' at the bottom of https://github.com/actions/runner-images/issues/6482, you can use [setup-node](https://github.com/actions/setup-node) action to indicate the Node version to use for your workflow.

**Comment by fhinkel** [comment]
👋  @StoyanStAtanasov Would you mind rebasing to resolve the merge conflict please. I'll ping @BALAGA-GAYATRI internally once it's ready. Thank you so much! 🙏  Really appreciate your efforts here!

**Comment by hargut** [comment]
What a mess... Isn't there a way to assign this issue to someone who can actually do the version upgrade?
It would be time to break that circuit of passing responsibility back and forth.

Further wasting peoples time by asking them to adjust their workflows to an intermediate resolution is also not a good option.

**Comment by BALAGA-GAYATRI** [comment]
We are working on these upgrades and planning to merge them soon.

**Comment by StoyanStAtanasov** [comment]
@fhinkel @BALAGA-GAYATRI I have updated the dev dependencies to solve the npm dependecy issue. I have created a basic devconfig to ensure codespaces uses the right node.js . There is also another PR against `releases/v1` as instructed in previous comments.
Also I was looking at the node.js roadmap and thinking maybe we should actually update to 18 LTS.
image
If so, then maybe now is the time to jump directly to 18. Just let me know and I can do another PR.

**Comment by fhinkel** [comment]
@StoyanStAtanasov Thanks so much for your help here! 🎉  Yes, if you don't mind creating another PR to go to 18, that would be better. Apologies that I didn't spot that in the review.

**Comment by sepulvedablanco** [comment]
@BALAGA-GAYATRI shouldn't the `v1` tag be updated to point to the last commit in `master`?

**Comment by BALAGA-GAYATRI** [comment]
Yeah that was pending. Just updated the tag. Please check. It should work now.

**Comment by sepulvedablanco** [comment]
I'll check, because now I get this error:

```
Run azure/docker-login@v1
  with:
    login-server: {MYLOGINSERVER}
    username: ***
    password: ***
  env:
    INTERNAL_REGISTRY_HOST: {MYREGISTRY}
    INTERNAL_REGISTRY_PATH: {MYPATH}
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/azure/docker-login/v1/lib/login.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:[2](https://github.com/inditex/lib-spinnakerdeploymentscripts/actions/runs/3522275015/jobs/5905060393#step:3:2)7)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/work/_actions/azure/docker-login/v1/lib/login.js:1[3](https://github.com/inditex/lib-spinnakerdeploymentscripts/actions/runs/3522275015/jobs/5905060393#step:3:3):1[4](https://github.com/inditex/lib-spinnakerdeploymentscripts/actions/runs/3522275015/jobs/5905060393#step:3:4))
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:11[5](https://github.com/inditex/lib-spinnakerdeploymentscripts/actions/runs/3522275015/jobs/5905060393#step:3:5)3:10)
    at Module.load (node:internal/modules/cjs/loader:9[8](https://github.com/inditex/lib-spinnakerdeploymentscripts/actions/runs/3522275015/jobs/5905060393#step:3:8)1:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:[12](https://github.com/inditex/lib-spinnakerdeploymentscripts/actions/runs/3522275015/jobs/5905060393#step:3:13))
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/_actions/azure/docker-login/v1/lib/login.js' ]
}
```

**Comment by sepulvedablanco** [comment]
I'll check, because now I get this error:

```
Run azure/docker-login@v1
  with:
    login-server: {MYLOGINSERVER}
    username: ***
    password: ***
  env:
    INTERNAL_REGISTRY_HOST: {MYREGISTRY}
    INTERNAL_REGISTRY_PATH: {MYPATH}
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/azure/docker-login/v1/lib/login.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/work/_actions/azure/docker-login/v1/lib/login.js:13:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/_actions/azure/docker-login/v1/lib/login.js' ]
}
```

**Comment by StoyanStAtanasov** [comment]
@fhinkel @BALAGA-GAYATRI I would love to do a PR to upgrade to Node.js-18 but I have a question: against which branch should I do it - `master` or `releases/v1`?

**Comment by mechelewskim** [comment]
@BALAGA-GAYATRI, I have the same issue as @sepulvedablanco
Currently, all workflows fail.

**Comment by BALAGA-GAYATRI** [comment]
Done the fix. Please check now. It should work!

**Comment by sepulvedablanco** [comment]
it works now. Thank you!

**Comment by StoyanStAtanasov** [comment]
@BALAGA-GAYATRI Did I do something wrong to create the error? 😟

**Comment by BALAGA-GAYATRI** [comment]
Nop. It was force push from a different that removed node_modules. No issues with the PR. Thanks for the contribution!

**Pull request merged**
